-- SQLite

-- Apagar tabela de funcionarios
DROP TABLE EMPLOYEES;

-- Tabela Employees
CREATE TABLE EMPLOYEES (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME VARCHAR(100) NOT NULL,
  LASTNAME TEXT NOT NULL,
  EMAIL TEXT NOT NULL,
  PASSWORD VARCHAR(20) NOT NULL,
  POSITION_ID INTEGER,
  STREET_ADDRESS TEXT NOT NULL,
  CITY VARCHAR(150) NOT NULL,
  STATE VARCHAR(2) NOT NULL,
  ZIP INTEGER NOT NULL,

  FOREIGN KEY (POSITION_ID) REFERENCES POSITIONS (ID)
);