-- SQLite

-- Tabela Providers
CREATE TABLE PROVIDERS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME VARCHAR(100) NOT NULL,
  REGISTER_NUMBER VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  STREET_ADDRESS TEXT NOT NULL,
  CITY TEXT NOT NULL,
  STATE VARCHAR(2) NOT NULL,
  ZIP INTEGER NOT NULL
);