-- SQLite

--Criando a tabela de Products
CREATE TABLE PRODUCTS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  PROVIDER_ID INTEGER,
  DESCRIPTION VARCHAR(200),
  PRICE DECIMAL(10,2),

  FOREIGN KEY (PROVIDER_ID) REFERENCES PROVIDERS (ID)
);