-- SQLite

--Criando a tabela de Sales
CREATE TABLE SALES (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CUSTOMER_ID INTEGER NOT NULL,
  EMPLOYEE_ID INTEGER NOT NULL,
  DATE_SALE DATETIME NOT NULL,
  TOTAL DECIMAL (10,2) NOT NULL,
  DESCRIPTION TEXT,

  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID)
  FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID)
);